if: tag =~ ^(\d+\.)?(\d+\.)?(\*|\d+)?(\*|\w+)?(\*|\d+)$
addons:
  ssh_known_hosts:
  - github.com
language: python
matrix:
  include:
  - name: Python 3.7.3 on macOS 10.14
    os: osx
    osx_image: xcode10.2
    language: shell
    before_install:
    - python3 --version
    - python3 -m pip install -U pip wheel setuptools
    - python3 -m pip install -U poetry
    install:
    - git checkout -qf $TRAVIS_COMMIT
    - python3 -m poetry install
    - python3 -m poetry run python version_writer.py $TRAVIS_TAG
    - cd src
    - python3 -m poetry run python cython-compiler.py -c -e UtopiaForReddit.py
    - cd ../
    script:
    - python3 -m poetry run justupdate -d build specs/mac.spec
    - python3 -m poetry run justupdate -d commit $TRAVIS_TAG
    - python3 -m poetry run justupdate -d upload -s gh-archive
    - git config --global user.email "NicklasMCHD@live.dk"
    - git config --global user.name "NicklasTegner"
    - git add .
    - git commit -m "Build version $TRAVIS_TAG on mac."
    - git push https://NicklasTegner:${GITHUB_TOKEN}@github.com/NicklasTegner/UtopiaForReddit.git HEAD:master
  - name: Python 3.7.3 on Windows
    os: windows
    language: shell
    before_install:
    - choco install nsis --no-progress -r --x86
    - export PATH=$PATH:";C:\Program Files (x86)\NSIS"
    - choco install python --no-progress -r --x86 --version 3.7.3
    - python --version
    - python -m pip install --upgrade pip
    - pip3 install -U pip wheel setuptools
    - pip3 install -U poetry
    install:
    - poetry install
    - poetry run python version_writer.py $TRAVIS_TAG
    - cd src
    - poetry run python cython-compiler.py -c -e UtopiaForReddit.py
    - cd ../
    script:
    - poetry run justupdate -d build specs/win-release.spec
    - poetry run justupdate -d commit $TRAVIS_TAG
    - poetry run justupdate -d upload -s gh-archive
    - git config --global user.email "NicklasMCHD@live.dk"
    - git config --global user.name "NicklasTegner"
    - git add .
    - git commit -m "Build version $TRAVIS_TAG on mac."
    - git push https://NicklasTegner:${GITHUB_TOKEN}@github.com/NicklasTegner/UtopiaForReddit.git HEAD:master
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
